from typing import Literal, Any

HELP_SECTIONS = [
    "Quick start",
    "Help guides",
    "Grid settings",
    "Control point settings",
    "Control point position window",
    "Bezier curve settings",
    "Controls",
    "Shortcuts",
    "Usage",
]

HELP_GUIDE_SELECTION: dict[str, dict[Literal["text", "tags", "codes"], str | dict[str, Any]]] = {
    "default": {
        "text": """""",
        "tags": {
            "SUBSCRIPT": {"font": ("Arial", 8), "offset": -3},
            "H1": {"font": ("Arial", 15, "bold")},
            "H2": {"font": ("Arial", 13, "bold")},
            "HYPERLINK": {"foreground": "blue", "underline": "True"},
            "UNDERLINE": {"underline": "True"},
            "STRIKETHROUGH": {"overstrike": "True"},
            "BOLD": {"font": ("Arial", 11, "bold")},
            "ITALIC": {"font": ("Arial", 11, "italic")},
            "RED": {"foreground": "red"},
        },
        "codes": {},
    },
    "Quick start": {
        "text": """[H1]Program function[H1/]\nThis program is to interactively generate any order Bezier curve given some number and position of control points.\nThis program was creation was just a sudden burst of motivation after talking about Bezier curves in a math class, so now enjoy this program [STRIKETHROUGH]modern art generator[STRIKETHROUGH/]\n\n[H1]UI basics[H1/]\nThe UI is split into 2 main parts, the canvas where the stuff is drawn, and the controls where you can change different settings that change the canvas.\n\nThe canvas takes up most of the window and it shrinks or grows to take up as large of a space in the window as possible. So for larger curves, a larger window is recommended, since the canvas would grow accordingly.\n\nThe controls take up a maximum width and sit on the right of the window. And within the controls, there are 4 main sections signified by the gray boxes.\nThe sections are labeled in bold "Grid settings", "Control point settings", "Bezier curve settings", and "Help".\nEach section contains controls for the respective name, so there are settings for the Bezier curve rendering in the "Bezier curve settings" section, etc.\nAnd at the bottom of the controls, there are 2 buttons, "Reset" and "Quit". Pressing the "Reset" button makes all the settings you changed reset to the default, and the defaults are just what the settings were when the window first opened. And pressing the "Quit" button closes the program.\n\n\n[H1]Control point basics[H1/]\nThe control points are the red circles in the canvas. These are what can be moved and are what dictate the shape of the Bezier curve.\n\nTo move the control points, just click one of them and drag it. Holding control while dragging makes it snap to the grid at different intervals (1/2 of grid unit by default). This interval can be changed (discussed in a different guide).\nHolding shift while dragging makes the point move either completely horizontally or vertically.\nHolding control and shift while dragging combines these effects.\n\nAnother way to move control points is to right click one of them and use the arrow keys to move the points by different intervals (1/4 of grid unit by default). This interval can be changed (discuss in a different guide).\n\n\n[H1]Bezier curve basics[H1/]\nThe blue collection of lines is the Bezier curve being drawn. This is the fancy thing you wanted to use the program to draw.\n\nThe curve is affected by the positions of the control points, so that\'s not able to be changed. But some things that can be changed are the curve resolution, linewidth, and whether or not to show the sampled points.\n\nThe way the curve works is by sampling points from the "true" Bezier curve and then drawing straight lines between the sampled points. So the curve resolution affects how many points are sampled. In simpler terms, lower resolution means a rougher curve. Higher resolution means a [ITALIC]smoother[ITALIC/] curve. This setting can be adjusted in the number input with the text "Curve resolution" above it.\n\nThe linewidth is just how [BOLD]THICC[BOLD/] to make the drawn curve. So a higher linewidth makes it thicker, and a lower linewidth makes it thinner. This setting can be adjusted in the number input with the text "Curve linewidth" above it.\n\nAs mentioned earlier, the curve is generated by sampling a bunch of points from the "true" Bezier curve, and there\'s a setting to show these sampled points. It can be turned on using the checkbox with the text "Show sampled points" next to it.""",
    },
    "Help guides": {
        "text": """""",
        "tags": {},
        "codes": {},
    },
    "Grid settings": {
        "text": """""",
        "tags": {},
        "codes": {},
    },
    "Control point settings": {
        "text": """""",
        "tags": {},
        "codes": {},
    },
    "Control point position window": {
        "text": """""",
        "tags": {},
        "codes": {},
    },
    "Bezier curve settings": {
        "text": """""",
        "tags": {},
        "codes": {},
    },
    "Controls": {
        "text": """""",
        "tags": {},
        "codes": {},
    },
    "Shortcuts": {
        "text": """""",
        "tags": {},
        "codes": {},
    },
    "Usage": {
        "text": """""",
        "tags": {},
        "codes": {},
    },
}
